"""
GitHub Issues Bot — auto-creates issues from infra events.
Called by FastAPI dispatcher when infra_event.github_issue=True.
Deduplication: same service+error_type twice in 24h → P1 escalation.
"""
import os
import json
import httpx
from datetime import datetime, timezone, timedelta
from pathlib import Path

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
GITHUB_REPO = os.getenv("GITHUB_REPO", "mnjbold/workflow-os")
DEDUP_STATE_FILE = Path.home() / ".openclaw" / "github-bot-dedup.json"

SEVERITY_LABELS = {
    "critical": ["bug", "infrastructure", "P0", "automated"],
    "high":     ["bug", "infrastructure", "P1", "automated"],
    "medium":   ["infrastructure", "P2", "automated"],
    "low":      ["infrastructure", "P3", "automated"],
}

def load_dedup_state() -> dict:
    if DEDUP_STATE_FILE.exists():
        return json.loads(DEDUP_STATE_FILE.read_text())
    return {"events": {}}

def save_dedup_state(state: dict):
    DEDUP_STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    DEDUP_STATE_FILE.write_text(json.dumps(state, indent=2))

def dedup_key(service: str, error_type: str) -> str:
    return f"{service}::{error_type}"

def check_and_update_dedup(service: str, error_type: str) -> tuple[bool, bool]:
    """Returns (should_create_issue, is_escalation)."""
    state = load_dedup_state()
    key = dedup_key(service, error_type)
    now = datetime.now(timezone.utc).isoformat()
    cutoff = (datetime.now(timezone.utc) - timedelta(hours=24)).isoformat()

    # Clean old entries
    state["events"] = {k: v for k, v in state["events"].items() if v["last_seen"] > cutoff}

    if key not in state["events"]:
        state["events"][key] = {"count": 1, "last_seen": now, "escalated": False}
        save_dedup_state(state)
        return True, False

    entry = state["events"][key]
    entry["count"] += 1
    entry["last_seen"] = now

    is_escalation = entry["count"] >= 2 and not entry.get("escalated", False)
    if is_escalation:
        entry["escalated"] = True

    save_dedup_state(state)
    return True, is_escalation

def create_github_issue(infra_event: dict) -> dict:
    """Create a GitHub issue from an infra event."""
    service = infra_event.get("service", "unknown")
    error_type = infra_event.get("error_type", "unknown")
    error_message = infra_event.get("error_message", "")
    severity = infra_event.get("severity", "medium")
    root_cause_hypothesis = infra_event.get("root_cause_hypothesis", "Investigation needed.")

    should_create, is_escalation = check_and_update_dedup(service, error_type)

    title_prefix = "🚨 [P0 ESCALATION]" if is_escalation else f"[INFRA]"
    title = f"{title_prefix} {service}: {error_type}"

    body = f"""## Infrastructure Event

**Service:** `{service}`
**Error Type:** `{error_type}`
**Severity:** `{severity}`
**Detected:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}

### Error Details
```
{error_message}
```

### Root Cause Hypothesis (Claude Analysis)
{root_cause_hypothesis}

### Suggested Actions
1. Check service logs for `{service}`
2. Verify infrastructure health at Coolify dashboard
3. Review recent deployments

{f'> ⚠️ **ESCALATION**: This error has occurred 2+ times in 24 hours. Immediate attention required.' if is_escalation else ''}

---
*Auto-generated by Workflow OS · EOD Report Parser*
"""

    labels = SEVERITY_LABELS.get(severity, ["infrastructure", "automated"])
    if is_escalation:
        labels = ["bug", "infrastructure", "P0", "automated", "escalation"]

    headers = {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }
    payload = {"title": title, "body": body, "labels": labels}

    resp = httpx.post(
        f"https://api.github.com/repos/{GITHUB_REPO}/issues",
        json=payload, headers=headers
    )
    resp.raise_for_status()
    issue = resp.json()
    print(f"  ✅ Issue #{issue['number']} created: {issue['html_url']}")
    return {"issue_number": issue["number"], "url": issue["html_url"], "escalated": is_escalation}

if __name__ == "__main__":
    # Test with a sample event
    test_event = {
        "service": "supabase",
        "error_type": "connection_refused",
        "error_message": "ECONNREFUSED 3.138.157.9:5432",
        "severity": "high",
        "root_cause_hypothesis": "PostgreSQL may be unreachable. Check EC2 security group rules for port 5432."
    }
    result = create_github_issue(test_event)
    print(json.dumps(result, indent=2))
